# Generated by Django 3.0.5 on 2020-04-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head1text',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head2text',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subhead21text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
