# Generated by Django 3.0.4 on 2020-03-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=10)),
                ('screenshot', models.ImageField(default='', upload_to='shop/images/contact')),
            ],
        ),
    ]
