# Generated by Django 3.0.4 on 2020-04-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200330_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('odr_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('zip', models.CharField(max_length=90)),
            ],
        ),
    ]
