# Generated by Django 3.0.4 on 2020-04-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200405_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='screenshot',
        ),
    ]
