# Generated by Django 3.0.6 on 2020-05-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
