# Generated by Django 3.0.6 on 2020-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bankid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
